#!/bin/sh

###################################################################################################
# dhcpc-event - Asuswrt-Merlin hook invoked on DHCP events
###################################################################################################

# Assign IPv6 to the SDN bridges
/jffs/scripts/sdn/sdn_v6_br.sh "$@"

# Apply static IPv6 routes
/jffs/scripts/misc/v6_static_routes.sh "$@"
