#!/bin/sh

###################################################################################################
# firewall-start - Asuswrt-Merlin hook invoked when the firewall stack reloads
###################################################################################################

# If the firewall restarted while the secondary WAN was active,
# reapply the LAN hosts WAN-block rule
/jffs/scripts/misc/wan_failover.sh "$1" "fw_started"

# Apply Tunnel Director rules
/jffs/scripts/firewall/tunnel_director.sh
