#!/bin/sh

###################################################################################################
# nat-start - Asuswrt-Merlin hook invoked when the NAT table is initialized:
#             reboot, WAN failover, etc.
###################################################################################################

# Filter inbound WAN traffic
/jffs/scripts/firewall/wan_firewall.sh

# Run WireGuard client port forwarding rules at NAT table (re)start
/jffs/scripts/wireguard/wgc_port_forwarder.sh
