#!/bin/sh

###################################################################################################
# pre-mount - Asuswrt-Merlin hook invoked before a block device is mounted
###################################################################################################

# SSD volume label assigned by tune2fs
SSD_VOLUME_LABEL='st5'    # <-- edit: change to your SSD's volume label

# If the device being mounted has the specified label, set its provisioning
# mode to "unmap" so the drive can be trimmed.
if tune2fs -l "$1" 2>/dev/null |
    grep -q "Filesystem volume name: *$SSD_VOLUME_LABEL$";
then
    /jffs/scripts/ssd/ssd_unmap.sh    # <-- edit: supply your vendor ID here if it isn't Samsung
fi
