#!/bin/sh

###################################################################################################
# wan-event - Asuswrt-Merlin hook invoked when a WAN interface goes up / down
###################################################################################################

# Hand off WAN events processing to the failover handler
/jffs/scripts/misc/wan_failover.sh "$@"
