#!/bin/sh

###################################################################################################
# wgclient-start - Asuswrt-Merlin hook invoked when a WireGuard client comes up
###################################################################################################

# Triggered when a WireGuard client comes up -> add its subnet route
/jffs/scripts/wireguard/wgc_route.sh add "$1"
