#!/bin/sh

###################################################################################################
# wgclient-stop - Asuswrt-Merlin hook invoked when a WireGuard client goes down
###################################################################################################

# Triggered when a WireGuard client goes down -> delete its subnet route
/jffs/scripts/wireguard/wgc_route.sh del "$1"
